### ISSUE TITLE
Node scenarios with Kraken on Single Node Openshift fail because it looks for "Unknown" status when the node is trying to recover from Chaos

### ISSUE THREAD

**Issue by Noreen21** [chaos-kubox/krkn#216]
Node scenarios (eg Node reboot) with Kraken on Single Node Openshift fail because it looks for `Unknown` status when the node is trying to recover from Chaos. SNO does not go to `Unknown` state, it directly goes from "Connection Timeout" to `Ready` state.

**Comment by jaredoconnell** [comment]
It appears that the check for the node status stalls when it can't connect. And it does so despite the timeout parameter because it's stalling on the status call within the function that looks for unknown status.

**Comment by paigerube14** [comment]
@Noreen21 I think I know how to fix this issue but would you be able to put the output from your run. I know it was run a while ago but that would help recreate this issue and give a fix

**Comment by jaredoconnell** [comment]
@paigerube14 It got stuck in here:
```
def wait_for_unknown_status(node, timeout):
    for _ in range(timeout):
        if kubecli.get_node_status(node) == "Unknown":
            break
        time.sleep(1)
    if kubecli.get_node_status(node) != "Unknown":
        raise Exception("Node condition status isn't Unknown")
```
It didn't have very valuable output, if I remember correctly. It just got stuck there.

This appears to happen because kraken expects enough nodes to be online to report the node status, but the only node that can report it is offline.

**Comment by Noreen21** [comment]
@paigerube14 I have the environment that can be used to test the fix. Let me know when you are ready.
